### ISSUE TITLE
[frontend] ログインボタンの遷移先をどうにかする

### ISSUE THREAD

**Issue by oribe1115** [isucon/isucon11-qualify#1450]
Homeで「JIAでログイン」ボタンを押すと`https://jia-auth.xi.isucon.dev`に飛ぶが、これは本番時以外は存在しないのでどうにかしてあげたほうがよさそう

**Comment by oribe1115** [comment]
`localhost:5000`にしておく？

**Comment by Mahito** [comment]
localhost:5000 が良さそう
